// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbAvgGetFullReadRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbAvgGetFullReadResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 sum = 1;</code>
   *
   * @return Whether the sum field is set.
   */
  boolean hasSum();

  /**
   * <code>required int64 sum = 1;</code>
   *
   * @return The sum.
   */
  long getSum();

  /**
   * <code>required int64 nAdds = 2;</code>
   *
   * @return Whether the nAdds field is set.
   */
  boolean hasNAdds();

  /**
   * <code>required int64 nAdds = 2;</code>
   *
   * @return The nAdds.
   */
  long getNAdds();
}
