// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbAverageUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbAverageUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 value = 1;</code>
   *
   * @return Whether the value field is set.
   */
  boolean hasValue();

  /**
   * <code>required int64 value = 1;</code>
   *
   * @return The value.
   */
  long getValue();

  /**
   * <code>optional int64 nValues = 2;</code>
   *
   * @return Whether the nValues field is set.
   */
  boolean hasNValues();

  /**
   * <code>optional int64 nValues = 2;</code>
   *
   * @return The nValues.
   */
  long getNValues();
}
