// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * Protobuf type {@code ApbAvgPartialReadResp}
 */
public final class ApbAvgPartialReadResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbAvgPartialReadResp)
    ApbAvgPartialReadRespOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbAvgPartialReadResp.newBuilder() to construct.
  private ApbAvgPartialReadResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbAvgPartialReadResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbAvgPartialReadResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbAvgPartialReadResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.arijo.protobuf.ApbAvgGetFullReadResp.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = getfull_.toBuilder();
            }
            getfull_ = input.readMessage(com.arijo.protobuf.ApbAvgGetFullReadResp.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(getfull_);
              getfull_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbAvgPartialReadResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbAvgPartialReadResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbAvgPartialReadResp.class, com.arijo.protobuf.ApbAvgPartialReadResp.Builder.class);
  }

  private int bitField0_;
  public static final int GETFULL_FIELD_NUMBER = 1;
  private com.arijo.protobuf.ApbAvgGetFullReadResp getfull_;

  /**
   * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
   *
   * @return Whether the getfull field is set.
   */
  @java.lang.Override
  public boolean hasGetfull() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
   *
   * @return The getfull.
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbAvgGetFullReadResp getGetfull() {
    return getfull_ == null ? com.arijo.protobuf.ApbAvgGetFullReadResp.getDefaultInstance() : getfull_;
  }

  /**
   * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbAvgGetFullReadRespOrBuilder getGetfullOrBuilder() {
    return getfull_ == null ? com.arijo.protobuf.ApbAvgGetFullReadResp.getDefaultInstance() : getfull_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasGetfull()) {
      if (!getGetfull().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGetfull());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGetfull());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbAvgPartialReadResp)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbAvgPartialReadResp other = (com.arijo.protobuf.ApbAvgPartialReadResp) obj;

    if (hasGetfull() != other.hasGetfull()) return false;
    if (hasGetfull()) {
      if (!getGetfull()
          .equals(other.getGetfull())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGetfull()) {
      hash = (37 * hash) + GETFULL_FIELD_NUMBER;
      hash = (53 * hash) + getGetfull().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbAvgPartialReadResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code ApbAvgPartialReadResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbAvgPartialReadResp)
      com.arijo.protobuf.ApbAvgPartialReadRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbAvgPartialReadResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbAvgPartialReadResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbAvgPartialReadResp.class, com.arijo.protobuf.ApbAvgPartialReadResp.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbAvgPartialReadResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getGetfullFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (getfullBuilder_ == null) {
        getfull_ = null;
      } else {
        getfullBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbAvgPartialReadResp_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbAvgPartialReadResp getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbAvgPartialReadResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbAvgPartialReadResp build() {
      com.arijo.protobuf.ApbAvgPartialReadResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbAvgPartialReadResp buildPartial() {
      com.arijo.protobuf.ApbAvgPartialReadResp result = new com.arijo.protobuf.ApbAvgPartialReadResp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (getfullBuilder_ == null) {
          result.getfull_ = getfull_;
        } else {
          result.getfull_ = getfullBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbAvgPartialReadResp) {
        return mergeFrom((com.arijo.protobuf.ApbAvgPartialReadResp) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbAvgPartialReadResp other) {
      if (other == com.arijo.protobuf.ApbAvgPartialReadResp.getDefaultInstance()) return this;
      if (other.hasGetfull()) {
        mergeGetfull(other.getGetfull());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (hasGetfull()) {
        if (!getGetfull().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbAvgPartialReadResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbAvgPartialReadResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.arijo.protobuf.ApbAvgGetFullReadResp getfull_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbAvgGetFullReadResp, com.arijo.protobuf.ApbAvgGetFullReadResp.Builder, com.arijo.protobuf.ApbAvgGetFullReadRespOrBuilder> getfullBuilder_;

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     *
     * @return Whether the getfull field is set.
     */
    public boolean hasGetfull() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     *
     * @return The getfull.
     */
    public com.arijo.protobuf.ApbAvgGetFullReadResp getGetfull() {
      if (getfullBuilder_ == null) {
        return getfull_ == null ? com.arijo.protobuf.ApbAvgGetFullReadResp.getDefaultInstance() : getfull_;
      } else {
        return getfullBuilder_.getMessage();
      }
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    public Builder setGetfull(com.arijo.protobuf.ApbAvgGetFullReadResp value) {
      if (getfullBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        getfull_ = value;
        onChanged();
      } else {
        getfullBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    public Builder setGetfull(
        com.arijo.protobuf.ApbAvgGetFullReadResp.Builder builderForValue) {
      if (getfullBuilder_ == null) {
        getfull_ = builderForValue.build();
        onChanged();
      } else {
        getfullBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    public Builder mergeGetfull(com.arijo.protobuf.ApbAvgGetFullReadResp value) {
      if (getfullBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            getfull_ != null &&
            getfull_ != com.arijo.protobuf.ApbAvgGetFullReadResp.getDefaultInstance()) {
          getfull_ =
              com.arijo.protobuf.ApbAvgGetFullReadResp.newBuilder(getfull_).mergeFrom(value).buildPartial();
        } else {
          getfull_ = value;
        }
        onChanged();
      } else {
        getfullBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    public Builder clearGetfull() {
      if (getfullBuilder_ == null) {
        getfull_ = null;
        onChanged();
      } else {
        getfullBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    public com.arijo.protobuf.ApbAvgGetFullReadResp.Builder getGetfullBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGetfullFieldBuilder().getBuilder();
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    public com.arijo.protobuf.ApbAvgGetFullReadRespOrBuilder getGetfullOrBuilder() {
      if (getfullBuilder_ != null) {
        return getfullBuilder_.getMessageOrBuilder();
      } else {
        return getfull_ == null ?
            com.arijo.protobuf.ApbAvgGetFullReadResp.getDefaultInstance() : getfull_;
      }
    }

    /**
     * <code>optional .ApbAvgGetFullReadResp getfull = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbAvgGetFullReadResp, com.arijo.protobuf.ApbAvgGetFullReadResp.Builder, com.arijo.protobuf.ApbAvgGetFullReadRespOrBuilder>
    getGetfullFieldBuilder() {
      if (getfullBuilder_ == null) {
        getfullBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.arijo.protobuf.ApbAvgGetFullReadResp, com.arijo.protobuf.ApbAvgGetFullReadResp.Builder, com.arijo.protobuf.ApbAvgGetFullReadRespOrBuilder>(
            getGetfull(),
            getParentForChildren(),
            isClean());
        getfull_ = null;
      }
      return getfullBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbAvgPartialReadResp)
  }

  // @@protoc_insertion_point(class_scope:ApbAvgPartialReadResp)
  private static final com.arijo.protobuf.ApbAvgPartialReadResp DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbAvgPartialReadResp();
  }

  public static com.arijo.protobuf.ApbAvgPartialReadResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbAvgPartialReadResp>
      PARSER = new com.google.protobuf.AbstractParser<ApbAvgPartialReadResp>() {
    @java.lang.Override
    public ApbAvgPartialReadResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbAvgPartialReadResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbAvgPartialReadResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbAvgPartialReadResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbAvgPartialReadResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

