// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbAvgPartialReadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbAvgPartialRead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ApbAvgFullRead getfull = 1;</code>
   *
   * @return Whether the getfull field is set.
   */
  boolean hasGetfull();

  /**
   * <code>optional .ApbAvgFullRead getfull = 1;</code>
   *
   * @return The getfull.
   */
  com.arijo.protobuf.ApbAvgFullRead getGetfull();

  /**
   * <code>optional .ApbAvgFullRead getfull = 1;</code>
   */
  com.arijo.protobuf.ApbAvgFullReadOrBuilder getGetfullOrBuilder();
}
