// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbAvgFullReadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbAvgFullRead)
    com.google.protobuf.MessageOrBuilder {
}
