// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbCommitTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbCommitTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes transaction_descriptor = 1;</code>
   *
   * @return Whether the transactionDescriptor field is set.
   */
  boolean hasTransactionDescriptor();

  /**
   * <code>required bytes transaction_descriptor = 1;</code>
   *
   * @return The transactionDescriptor.
   */
  com.google.protobuf.ByteString getTransactionDescriptor();
}
