// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbConnectReplicaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbConnectReplica)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   *
   * @return Whether the id field is set.
   */
  boolean hasId();

  /**
   * <code>required int64 id = 1;</code>
   *
   * @return The id.
   */
  long getId();
}
