// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbConnectReplicaRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbConnectReplicaResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 knownIDs = 1;</code>
   *
   * @return A list containing the knownIDs.
   */
  java.util.List<java.lang.Long> getKnownIDsList();

  /**
   * <code>repeated int64 knownIDs = 1;</code>
   *
   * @return The count of knownIDs.
   */
  int getKnownIDsCount();

  /**
   * <code>repeated int64 knownIDs = 1;</code>
   *
   * @param index The index of the element to return.
   * @return The knownIDs at the given index.
   */
  long getKnownIDs(int index);
}
