// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbGetMaxMinRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbGetMaxMinResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 value = 1;</code>
   *
   * @return Whether the value field is set.
   */
  boolean hasValue();

  /**
   * <code>required int64 value = 1;</code>
   *
   * @return The value.
   */
  long getValue();
}
