// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * Protobuf type {@code ApbLeaderboardUpdate}
 */
public final class ApbLeaderboardUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbLeaderboardUpdate)
    ApbLeaderboardUpdateOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbLeaderboardUpdate.newBuilder() to construct.
  private ApbLeaderboardUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbLeaderboardUpdate() {
    adds_ = java.util.Collections.emptyList();
    rems_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbLeaderboardUpdate();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbLeaderboardUpdate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              adds_ = new java.util.ArrayList<com.arijo.protobuf.ApbIntPair>();
              mutable_bitField0_ |= 0x00000001;
            }
            adds_.add(
                input.readMessage(com.arijo.protobuf.ApbIntPair.PARSER, extensionRegistry));
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              rems_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            rems_.addInt(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              rems_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              rems_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        adds_ = java.util.Collections.unmodifiableList(adds_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        rems_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbLeaderboardUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbLeaderboardUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbLeaderboardUpdate.class, com.arijo.protobuf.ApbLeaderboardUpdate.Builder.class);
  }

  public static final int ADDS_FIELD_NUMBER = 1;
  private java.util.List<com.arijo.protobuf.ApbIntPair> adds_;

  /**
   * <code>repeated .ApbIntPair adds = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.arijo.protobuf.ApbIntPair> getAddsList() {
    return adds_;
  }

  /**
   * <code>repeated .ApbIntPair adds = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.arijo.protobuf.ApbIntPairOrBuilder>
  getAddsOrBuilderList() {
    return adds_;
  }

  /**
   * <code>repeated .ApbIntPair adds = 1;</code>
   */
  @java.lang.Override
  public int getAddsCount() {
    return adds_.size();
  }

  /**
   * <code>repeated .ApbIntPair adds = 1;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbIntPair getAdds(int index) {
    return adds_.get(index);
  }

  /**
   * <code>repeated .ApbIntPair adds = 1;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbIntPairOrBuilder getAddsOrBuilder(
      int index) {
    return adds_.get(index);
  }

  public static final int REMS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.IntList rems_;

  /**
   * <code>repeated int32 rems = 2;</code>
   *
   * @return A list containing the rems.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getRemsList() {
    return rems_;
  }

  /**
   * <code>repeated int32 rems = 2;</code>
   *
   * @return The count of rems.
   */
  public int getRemsCount() {
    return rems_.size();
  }

  /**
   * <code>repeated int32 rems = 2;</code>
   *
   * @param index The index of the element to return.
   * @return The rems at the given index.
   */
  public int getRems(int index) {
    return rems_.getInt(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getAddsCount(); i++) {
      if (!getAdds(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    for (int i = 0; i < adds_.size(); i++) {
      output.writeMessage(1, adds_.get(i));
    }
    for (int i = 0; i < rems_.size(); i++) {
      output.writeInt32(2, rems_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < adds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, adds_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < rems_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(rems_.getInt(i));
      }
      size += dataSize;
      size += 1 * getRemsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbLeaderboardUpdate)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbLeaderboardUpdate other = (com.arijo.protobuf.ApbLeaderboardUpdate) obj;

    if (!getAddsList()
        .equals(other.getAddsList())) return false;
    if (!getRemsList()
        .equals(other.getRemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAddsCount() > 0) {
      hash = (37 * hash) + ADDS_FIELD_NUMBER;
      hash = (53 * hash) + getAddsList().hashCode();
    }
    if (getRemsCount() > 0) {
      hash = (37 * hash) + REMS_FIELD_NUMBER;
      hash = (53 * hash) + getRemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbLeaderboardUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code ApbLeaderboardUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbLeaderboardUpdate)
      com.arijo.protobuf.ApbLeaderboardUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbLeaderboardUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbLeaderboardUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbLeaderboardUpdate.class, com.arijo.protobuf.ApbLeaderboardUpdate.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbLeaderboardUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getAddsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (addsBuilder_ == null) {
        adds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        addsBuilder_.clear();
      }
      rems_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbLeaderboardUpdate_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbLeaderboardUpdate getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbLeaderboardUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbLeaderboardUpdate build() {
      com.arijo.protobuf.ApbLeaderboardUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbLeaderboardUpdate buildPartial() {
      com.arijo.protobuf.ApbLeaderboardUpdate result = new com.arijo.protobuf.ApbLeaderboardUpdate(this);
      int from_bitField0_ = bitField0_;
      if (addsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          adds_ = java.util.Collections.unmodifiableList(adds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.adds_ = adds_;
      } else {
        result.adds_ = addsBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        rems_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.rems_ = rems_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbLeaderboardUpdate) {
        return mergeFrom((com.arijo.protobuf.ApbLeaderboardUpdate) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbLeaderboardUpdate other) {
      if (other == com.arijo.protobuf.ApbLeaderboardUpdate.getDefaultInstance()) return this;
      if (addsBuilder_ == null) {
        if (!other.adds_.isEmpty()) {
          if (adds_.isEmpty()) {
            adds_ = other.adds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddsIsMutable();
            adds_.addAll(other.adds_);
          }
          onChanged();
        }
      } else {
        if (!other.adds_.isEmpty()) {
          if (addsBuilder_.isEmpty()) {
            addsBuilder_.dispose();
            addsBuilder_ = null;
            adds_ = other.adds_;
            bitField0_ = (bitField0_ & ~0x00000001);
            addsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                    getAddsFieldBuilder() : null;
          } else {
            addsBuilder_.addAllMessages(other.adds_);
          }
        }
      }
      if (!other.rems_.isEmpty()) {
        if (rems_.isEmpty()) {
          rems_ = other.rems_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRemsIsMutable();
          rems_.addAll(other.rems_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getAddsCount(); i++) {
        if (!getAdds(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbLeaderboardUpdate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbLeaderboardUpdate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.util.List<com.arijo.protobuf.ApbIntPair> adds_ =
        java.util.Collections.emptyList();

    private void ensureAddsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        adds_ = new java.util.ArrayList<com.arijo.protobuf.ApbIntPair>(adds_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.arijo.protobuf.ApbIntPair, com.arijo.protobuf.ApbIntPair.Builder, com.arijo.protobuf.ApbIntPairOrBuilder> addsBuilder_;

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public java.util.List<com.arijo.protobuf.ApbIntPair> getAddsList() {
      if (addsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(adds_);
      } else {
        return addsBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public int getAddsCount() {
      if (addsBuilder_ == null) {
        return adds_.size();
      } else {
        return addsBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public com.arijo.protobuf.ApbIntPair getAdds(int index) {
      if (addsBuilder_ == null) {
        return adds_.get(index);
      } else {
        return addsBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder setAdds(
        int index, com.arijo.protobuf.ApbIntPair value) {
      if (addsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddsIsMutable();
        adds_.set(index, value);
        onChanged();
      } else {
        addsBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder setAdds(
        int index, com.arijo.protobuf.ApbIntPair.Builder builderForValue) {
      if (addsBuilder_ == null) {
        ensureAddsIsMutable();
        adds_.set(index, builderForValue.build());
        onChanged();
      } else {
        addsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder addAdds(com.arijo.protobuf.ApbIntPair value) {
      if (addsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddsIsMutable();
        adds_.add(value);
        onChanged();
      } else {
        addsBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder addAdds(
        int index, com.arijo.protobuf.ApbIntPair value) {
      if (addsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddsIsMutable();
        adds_.add(index, value);
        onChanged();
      } else {
        addsBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder addAdds(
        com.arijo.protobuf.ApbIntPair.Builder builderForValue) {
      if (addsBuilder_ == null) {
        ensureAddsIsMutable();
        adds_.add(builderForValue.build());
        onChanged();
      } else {
        addsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder addAdds(
        int index, com.arijo.protobuf.ApbIntPair.Builder builderForValue) {
      if (addsBuilder_ == null) {
        ensureAddsIsMutable();
        adds_.add(index, builderForValue.build());
        onChanged();
      } else {
        addsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder addAllAdds(
        java.lang.Iterable<? extends com.arijo.protobuf.ApbIntPair> values) {
      if (addsBuilder_ == null) {
        ensureAddsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, adds_);
        onChanged();
      } else {
        addsBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder clearAdds() {
      if (addsBuilder_ == null) {
        adds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        addsBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public Builder removeAdds(int index) {
      if (addsBuilder_ == null) {
        ensureAddsIsMutable();
        adds_.remove(index);
        onChanged();
      } else {
        addsBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public com.arijo.protobuf.ApbIntPair.Builder getAddsBuilder(
        int index) {
      return getAddsFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public com.arijo.protobuf.ApbIntPairOrBuilder getAddsOrBuilder(
        int index) {
      if (addsBuilder_ == null) {
        return adds_.get(index);
      } else {
        return addsBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public java.util.List<? extends com.arijo.protobuf.ApbIntPairOrBuilder>
    getAddsOrBuilderList() {
      if (addsBuilder_ != null) {
        return addsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(adds_);
      }
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public com.arijo.protobuf.ApbIntPair.Builder addAddsBuilder() {
      return getAddsFieldBuilder().addBuilder(
          com.arijo.protobuf.ApbIntPair.getDefaultInstance());
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public com.arijo.protobuf.ApbIntPair.Builder addAddsBuilder(
        int index) {
      return getAddsFieldBuilder().addBuilder(
          index, com.arijo.protobuf.ApbIntPair.getDefaultInstance());
    }

    /**
     * <code>repeated .ApbIntPair adds = 1;</code>
     */
    public java.util.List<com.arijo.protobuf.ApbIntPair.Builder>
    getAddsBuilderList() {
      return getAddsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.arijo.protobuf.ApbIntPair, com.arijo.protobuf.ApbIntPair.Builder, com.arijo.protobuf.ApbIntPairOrBuilder>
    getAddsFieldBuilder() {
      if (addsBuilder_ == null) {
        addsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.arijo.protobuf.ApbIntPair, com.arijo.protobuf.ApbIntPair.Builder, com.arijo.protobuf.ApbIntPairOrBuilder>(
            adds_,
            ((bitField0_ & 0x00000001) != 0),
            getParentForChildren(),
            isClean());
        adds_ = null;
      }
      return addsBuilder_;
    }

    private com.google.protobuf.Internal.IntList rems_ = emptyIntList();

    private void ensureRemsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        rems_ = mutableCopy(rems_);
        bitField0_ |= 0x00000002;
      }
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @return A list containing the rems.
     */
    public java.util.List<java.lang.Integer>
    getRemsList() {
      return ((bitField0_ & 0x00000002) != 0) ?
          java.util.Collections.unmodifiableList(rems_) : rems_;
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @return The count of rems.
     */
    public int getRemsCount() {
      return rems_.size();
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The rems at the given index.
     */
    public int getRems(int index) {
      return rems_.getInt(index);
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @param index The index to set the value at.
     * @param value The rems to set.
     * @return This builder for chaining.
     */
    public Builder setRems(
        int index, int value) {
      ensureRemsIsMutable();
      rems_.setInt(index, value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @param value The rems to add.
     * @return This builder for chaining.
     */
    public Builder addRems(int value) {
      ensureRemsIsMutable();
      rems_.addInt(value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @param values The rems to add.
     * @return This builder for chaining.
     */
    public Builder addAllRems(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureRemsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, rems_);
      onChanged();
      return this;
    }

    /**
     * <code>repeated int32 rems = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRems() {
      rems_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbLeaderboardUpdate)
  }

  // @@protoc_insertion_point(class_scope:ApbLeaderboardUpdate)
  private static final com.arijo.protobuf.ApbLeaderboardUpdate DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbLeaderboardUpdate();
  }

  public static com.arijo.protobuf.ApbLeaderboardUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbLeaderboardUpdate>
      PARSER = new com.google.protobuf.AbstractParser<ApbLeaderboardUpdate>() {
    @java.lang.Override
    public ApbLeaderboardUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbLeaderboardUpdate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbLeaderboardUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbLeaderboardUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbLeaderboardUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

