// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbMapPartialReadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbMapPartialRead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ApbMapGetValueRead getvalue = 1;</code>
   *
   * @return Whether the getvalue field is set.
   */
  boolean hasGetvalue();

  /**
   * <code>optional .ApbMapGetValueRead getvalue = 1;</code>
   *
   * @return The getvalue.
   */
  com.arijo.protobuf.ApbMapGetValueRead getGetvalue();

  /**
   * <code>optional .ApbMapGetValueRead getvalue = 1;</code>
   */
  com.arijo.protobuf.ApbMapGetValueReadOrBuilder getGetvalueOrBuilder();

  /**
   * <code>optional .ApbMapHasKeyRead haskey = 2;</code>
   *
   * @return Whether the haskey field is set.
   */
  boolean hasHaskey();

  /**
   * <code>optional .ApbMapHasKeyRead haskey = 2;</code>
   *
   * @return The haskey.
   */
  com.arijo.protobuf.ApbMapHasKeyRead getHaskey();

  /**
   * <code>optional .ApbMapHasKeyRead haskey = 2;</code>
   */
  com.arijo.protobuf.ApbMapHasKeyReadOrBuilder getHaskeyOrBuilder();

  /**
   * <code>optional .ApbMapGetKeysRead getkeys = 3;</code>
   *
   * @return Whether the getkeys field is set.
   */
  boolean hasGetkeys();

  /**
   * <code>optional .ApbMapGetKeysRead getkeys = 3;</code>
   *
   * @return The getkeys.
   */
  com.arijo.protobuf.ApbMapGetKeysRead getGetkeys();

  /**
   * <code>optional .ApbMapGetKeysRead getkeys = 3;</code>
   */
  com.arijo.protobuf.ApbMapGetKeysReadOrBuilder getGetkeysOrBuilder();

  /**
   * <code>optional .ApbMapGetValuesRead getvalues = 4;</code>
   *
   * @return Whether the getvalues field is set.
   */
  boolean hasGetvalues();

  /**
   * <code>optional .ApbMapGetValuesRead getvalues = 4;</code>
   *
   * @return The getvalues.
   */
  com.arijo.protobuf.ApbMapGetValuesRead getGetvalues();

  /**
   * <code>optional .ApbMapGetValuesRead getvalues = 4;</code>
   */
  com.arijo.protobuf.ApbMapGetValuesReadOrBuilder getGetvaluesOrBuilder();
}
