// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbMaxMinUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbMaxMinUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 value = 1;</code>
   *
   * @return Whether the value field is set.
   */
  boolean hasValue();

  /**
   * <code>required int64 value = 1;</code>
   *
   * @return The value.
   */
  long getValue();

  /**
   * <code>required bool isMax = 2;</code>
   *
   * @return Whether the isMax field is set.
   */
  boolean hasIsMax();

  /**
   * <code>required bool isMax = 2;</code>
   *
   * @return The isMax.
   */
  boolean getIsMax();
}
