// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbMapGetValueReadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbMapGetValueRead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes key = 1;</code>
   *
   * @return Whether the key field is set.
   */
  boolean hasKey();

  /**
   * <code>required bytes key = 1;</code>
   *
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>optional .ApbMapEmbPartialArgs args = 2;</code>
   *
   * @return Whether the args field is set.
   */
  boolean hasArgs();

  /**
   * <code>optional .ApbMapEmbPartialArgs args = 2;</code>
   *
   * @return The args.
   */
  com.arijo.protobuf.ApbMapEmbPartialArgs getArgs();

  /**
   * <code>optional .ApbMapEmbPartialArgs args = 2;</code>
   */
  com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder getArgsOrBuilder();
}
