// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * <pre>
 * Helper for identifying a partial read of an embedded CRDT
 * </pre>
 * <p>
 * Protobuf type {@code ApbMapEmbPartialArgs}
 */
public final class ApbMapEmbPartialArgs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbMapEmbPartialArgs)
    ApbMapEmbPartialArgsOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbMapEmbPartialArgs.newBuilder() to construct.
  private ApbMapEmbPartialArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbMapEmbPartialArgs() {
    type_ = 3;
    readtype_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbMapEmbPartialArgs();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbMapEmbPartialArgs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
            @SuppressWarnings("deprecation")
            com.arijo.protobuf.CRDT_type value = com.arijo.protobuf.CRDT_type.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              type_ = rawValue;
            }
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            @SuppressWarnings("deprecation")
            com.arijo.protobuf.READ_type value = com.arijo.protobuf.READ_type.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              readtype_ = rawValue;
            }
            break;
          }
          case 26: {
            com.arijo.protobuf.ApbPartialReadArgs.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = args_.toBuilder();
            }
            args_ = input.readMessage(com.arijo.protobuf.ApbPartialReadArgs.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(args_);
              args_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbMapEmbPartialArgs_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbMapEmbPartialArgs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbMapEmbPartialArgs.class, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;

  /**
   * <code>optional .CRDT_type type = 1;</code>
   *
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>optional .CRDT_type type = 1;</code>
   *
   * @return The type.
   */
  @java.lang.Override
  public com.arijo.protobuf.CRDT_type getType() {
    @SuppressWarnings("deprecation")
    com.arijo.protobuf.CRDT_type result = com.arijo.protobuf.CRDT_type.valueOf(type_);
    return result == null ? com.arijo.protobuf.CRDT_type.COUNTER : result;
  }

  public static final int READTYPE_FIELD_NUMBER = 2;
  private int readtype_;

  /**
   * <code>required .READ_type readtype = 2;</code>
   *
   * @return Whether the readtype field is set.
   */
  @java.lang.Override
  public boolean hasReadtype() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>required .READ_type readtype = 2;</code>
   *
   * @return The readtype.
   */
  @java.lang.Override
  public com.arijo.protobuf.READ_type getReadtype() {
    @SuppressWarnings("deprecation")
    com.arijo.protobuf.READ_type result = com.arijo.protobuf.READ_type.valueOf(readtype_);
    return result == null ? com.arijo.protobuf.READ_type.FULL : result;
  }

  public static final int ARGS_FIELD_NUMBER = 3;
  private com.arijo.protobuf.ApbPartialReadArgs args_;

  /**
   * <pre>
   * If not present, then it's a full read
   * </pre>
   *
   * <code>optional .ApbPartialReadArgs args = 3;</code>
   *
   * @return Whether the args field is set.
   */
  @java.lang.Override
  public boolean hasArgs() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <pre>
   * If not present, then it's a full read
   * </pre>
   *
   * <code>optional .ApbPartialReadArgs args = 3;</code>
   *
   * @return The args.
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbPartialReadArgs getArgs() {
    return args_ == null ? com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
  }

  /**
   * <pre>
   * If not present, then it's a full read
   * </pre>
   *
   * <code>optional .ApbPartialReadArgs args = 3;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbPartialReadArgsOrBuilder getArgsOrBuilder() {
    return args_ == null ? com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasReadtype()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasArgs()) {
      if (!getArgs().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, type_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, readtype_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getArgs());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, readtype_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getArgs());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbMapEmbPartialArgs)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbMapEmbPartialArgs other = (com.arijo.protobuf.ApbMapEmbPartialArgs) obj;

    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (hasReadtype() != other.hasReadtype()) return false;
    if (hasReadtype()) {
      if (readtype_ != other.readtype_) return false;
    }
    if (hasArgs() != other.hasArgs()) return false;
    if (hasArgs()) {
      if (!getArgs()
          .equals(other.getArgs())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    if (hasReadtype()) {
      hash = (37 * hash) + READTYPE_FIELD_NUMBER;
      hash = (53 * hash) + readtype_;
    }
    if (hasArgs()) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgs().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbMapEmbPartialArgs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * Helper for identifying a partial read of an embedded CRDT
   * </pre>
   * <p>
   * Protobuf type {@code ApbMapEmbPartialArgs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbMapEmbPartialArgs)
      com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbMapEmbPartialArgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbMapEmbPartialArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbMapEmbPartialArgs.class, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbMapEmbPartialArgs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getArgsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 3;
      bitField0_ = (bitField0_ & ~0x00000001);
      readtype_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (argsBuilder_ == null) {
        args_ = null;
      } else {
        argsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbMapEmbPartialArgs_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbMapEmbPartialArgs getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbMapEmbPartialArgs.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbMapEmbPartialArgs build() {
      com.arijo.protobuf.ApbMapEmbPartialArgs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbMapEmbPartialArgs buildPartial() {
      com.arijo.protobuf.ApbMapEmbPartialArgs result = new com.arijo.protobuf.ApbMapEmbPartialArgs(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.readtype_ = readtype_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (argsBuilder_ == null) {
          result.args_ = args_;
        } else {
          result.args_ = argsBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbMapEmbPartialArgs) {
        return mergeFrom((com.arijo.protobuf.ApbMapEmbPartialArgs) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbMapEmbPartialArgs other) {
      if (other == com.arijo.protobuf.ApbMapEmbPartialArgs.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasReadtype()) {
        setReadtype(other.getReadtype());
      }
      if (other.hasArgs()) {
        mergeArgs(other.getArgs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasReadtype()) {
        return false;
      }
      if (hasArgs()) {
        if (!getArgs().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbMapEmbPartialArgs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbMapEmbPartialArgs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private int type_ = 3;

    /**
     * <code>optional .CRDT_type type = 1;</code>
     *
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional .CRDT_type type = 1;</code>
     *
     * @return The type.
     */
    @java.lang.Override
    public com.arijo.protobuf.CRDT_type getType() {
      @SuppressWarnings("deprecation")
      com.arijo.protobuf.CRDT_type result = com.arijo.protobuf.CRDT_type.valueOf(type_);
      return result == null ? com.arijo.protobuf.CRDT_type.COUNTER : result;
    }

    /**
     * <code>optional .CRDT_type type = 1;</code>
     *
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.arijo.protobuf.CRDT_type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <code>optional .CRDT_type type = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 3;
      onChanged();
      return this;
    }

    private int readtype_ = 0;

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @return Whether the readtype field is set.
     */
    @java.lang.Override
    public boolean hasReadtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @return The readtype.
     */
    @java.lang.Override
    public com.arijo.protobuf.READ_type getReadtype() {
      @SuppressWarnings("deprecation")
      com.arijo.protobuf.READ_type result = com.arijo.protobuf.READ_type.valueOf(readtype_);
      return result == null ? com.arijo.protobuf.READ_type.FULL : result;
    }

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @param value The readtype to set.
     * @return This builder for chaining.
     */
    public Builder setReadtype(com.arijo.protobuf.READ_type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      readtype_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearReadtype() {
      bitField0_ = (bitField0_ & ~0x00000002);
      readtype_ = 0;
      onChanged();
      return this;
    }

    private com.arijo.protobuf.ApbPartialReadArgs args_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbPartialReadArgs, com.arijo.protobuf.ApbPartialReadArgs.Builder, com.arijo.protobuf.ApbPartialReadArgsOrBuilder> argsBuilder_;

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     *
     * @return Whether the args field is set.
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     *
     * @return The args.
     */
    public com.arijo.protobuf.ApbPartialReadArgs getArgs() {
      if (argsBuilder_ == null) {
        return args_ == null ? com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
      } else {
        return argsBuilder_.getMessage();
      }
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    public Builder setArgs(com.arijo.protobuf.ApbPartialReadArgs value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        args_ = value;
        onChanged();
      } else {
        argsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    public Builder setArgs(
        com.arijo.protobuf.ApbPartialReadArgs.Builder builderForValue) {
      if (argsBuilder_ == null) {
        args_ = builderForValue.build();
        onChanged();
      } else {
        argsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    public Builder mergeArgs(com.arijo.protobuf.ApbPartialReadArgs value) {
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            args_ != null &&
            args_ != com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance()) {
          args_ =
              com.arijo.protobuf.ApbPartialReadArgs.newBuilder(args_).mergeFrom(value).buildPartial();
        } else {
          args_ = value;
        }
        onChanged();
      } else {
        argsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    public Builder clearArgs() {
      if (argsBuilder_ == null) {
        args_ = null;
        onChanged();
      } else {
        argsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    public com.arijo.protobuf.ApbPartialReadArgs.Builder getArgsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getArgsFieldBuilder().getBuilder();
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    public com.arijo.protobuf.ApbPartialReadArgsOrBuilder getArgsOrBuilder() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilder();
      } else {
        return args_ == null ?
            com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
      }
    }

    /**
     * <pre>
     * If not present, then it's a full read
     * </pre>
     *
     * <code>optional .ApbPartialReadArgs args = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbPartialReadArgs, com.arijo.protobuf.ApbPartialReadArgs.Builder, com.arijo.protobuf.ApbPartialReadArgsOrBuilder>
    getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.arijo.protobuf.ApbPartialReadArgs, com.arijo.protobuf.ApbPartialReadArgs.Builder, com.arijo.protobuf.ApbPartialReadArgsOrBuilder>(
            getArgs(),
            getParentForChildren(),
            isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbMapEmbPartialArgs)
  }

  // @@protoc_insertion_point(class_scope:ApbMapEmbPartialArgs)
  private static final com.arijo.protobuf.ApbMapEmbPartialArgs DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbMapEmbPartialArgs();
  }

  public static com.arijo.protobuf.ApbMapEmbPartialArgs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbMapEmbPartialArgs>
      PARSER = new com.google.protobuf.AbstractParser<ApbMapEmbPartialArgs>() {
    @java.lang.Override
    public ApbMapEmbPartialArgs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbMapEmbPartialArgs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbMapEmbPartialArgs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbMapEmbPartialArgs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbMapEmbPartialArgs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

