// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbMapNestedUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbMapNestedUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ApbMapKey key = 1;</code>
   *
   * @return Whether the key field is set.
   */
  boolean hasKey();

  /**
   * <code>required .ApbMapKey key = 1;</code>
   *
   * @return The key.
   */
  com.arijo.protobuf.ApbMapKey getKey();

  /**
   * <code>required .ApbMapKey key = 1;</code>
   */
  com.arijo.protobuf.ApbMapKeyOrBuilder getKeyOrBuilder();

  /**
   * <code>required .ApbUpdateOperation update = 2;</code>
   *
   * @return Whether the update field is set.
   */
  boolean hasUpdate();

  /**
   * <code>required .ApbUpdateOperation update = 2;</code>
   *
   * @return The update.
   */
  com.arijo.protobuf.ApbUpdateOperation getUpdate();

  /**
   * <code>required .ApbUpdateOperation update = 2;</code>
   */
  com.arijo.protobuf.ApbUpdateOperationOrBuilder getUpdateOrBuilder();
}
