// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * <pre>
 * Note: The 2nd argument is optional.
 * However, if it's present, then its len must be equal to keys'
 * </pre>
 * <p>
 * Protobuf type {@code ApbMapGetValuesRead}
 */
public final class ApbMapGetValuesRead extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbMapGetValuesRead)
    ApbMapGetValuesReadOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbMapGetValuesRead.newBuilder() to construct.
  private ApbMapGetValuesRead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbMapGetValuesRead() {
    keys_ = java.util.Collections.emptyList();
    args_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbMapGetValuesRead();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbMapGetValuesRead(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              keys_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
              mutable_bitField0_ |= 0x00000001;
            }
            keys_.add(input.readBytes());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              args_ = new java.util.ArrayList<com.arijo.protobuf.ApbMapEmbPartialArgs>();
              mutable_bitField0_ |= 0x00000002;
            }
            args_.add(
                input.readMessage(com.arijo.protobuf.ApbMapEmbPartialArgs.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        keys_ = java.util.Collections.unmodifiableList(keys_); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        args_ = java.util.Collections.unmodifiableList(args_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbMapGetValuesRead_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbMapGetValuesRead_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbMapGetValuesRead.class, com.arijo.protobuf.ApbMapGetValuesRead.Builder.class);
  }

  public static final int KEYS_FIELD_NUMBER = 1;
  private java.util.List<com.google.protobuf.ByteString> keys_;

  /**
   * <code>repeated bytes keys = 1;</code>
   *
   * @return A list containing the keys.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
  getKeysList() {
    return keys_;
  }

  /**
   * <code>repeated bytes keys = 1;</code>
   *
   * @return The count of keys.
   */
  public int getKeysCount() {
    return keys_.size();
  }

  /**
   * <code>repeated bytes keys = 1;</code>
   *
   * @param index The index of the element to return.
   * @return The keys at the given index.
   */
  public com.google.protobuf.ByteString getKeys(int index) {
    return keys_.get(index);
  }

  public static final int ARGS_FIELD_NUMBER = 2;
  private java.util.List<com.arijo.protobuf.ApbMapEmbPartialArgs> args_;

  /**
   * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.arijo.protobuf.ApbMapEmbPartialArgs> getArgsList() {
    return args_;
  }

  /**
   * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder>
  getArgsOrBuilderList() {
    return args_;
  }

  /**
   * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
   */
  @java.lang.Override
  public int getArgsCount() {
    return args_.size();
  }

  /**
   * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbMapEmbPartialArgs getArgs(int index) {
    return args_.get(index);
  }

  /**
   * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder getArgsOrBuilder(
      int index) {
    return args_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getArgsCount(); i++) {
      if (!getArgs(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    for (int i = 0; i < keys_.size(); i++) {
      output.writeBytes(1, keys_.get(i));
    }
    for (int i = 0; i < args_.size(); i++) {
      output.writeMessage(2, args_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < keys_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(keys_.get(i));
      }
      size += dataSize;
      size += 1 * getKeysList().size();
    }
    for (int i = 0; i < args_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, args_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbMapGetValuesRead)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbMapGetValuesRead other = (com.arijo.protobuf.ApbMapGetValuesRead) obj;

    if (!getKeysList()
        .equals(other.getKeysList())) return false;
    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKeysCount() > 0) {
      hash = (37 * hash) + KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getKeysList().hashCode();
    }
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbMapGetValuesRead prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * Note: The 2nd argument is optional.
   * However, if it's present, then its len must be equal to keys'
   * </pre>
   * <p>
   * Protobuf type {@code ApbMapGetValuesRead}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbMapGetValuesRead)
      com.arijo.protobuf.ApbMapGetValuesReadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbMapGetValuesRead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbMapGetValuesRead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbMapGetValuesRead.class, com.arijo.protobuf.ApbMapGetValuesRead.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbMapGetValuesRead.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getArgsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      keys_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        argsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbMapGetValuesRead_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbMapGetValuesRead getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbMapGetValuesRead.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbMapGetValuesRead build() {
      com.arijo.protobuf.ApbMapGetValuesRead result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbMapGetValuesRead buildPartial() {
      com.arijo.protobuf.ApbMapGetValuesRead result = new com.arijo.protobuf.ApbMapGetValuesRead(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        keys_ = java.util.Collections.unmodifiableList(keys_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.keys_ = keys_;
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.args_ = args_;
      } else {
        result.args_ = argsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbMapGetValuesRead) {
        return mergeFrom((com.arijo.protobuf.ApbMapGetValuesRead) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbMapGetValuesRead other) {
      if (other == com.arijo.protobuf.ApbMapGetValuesRead.getDefaultInstance()) return this;
      if (!other.keys_.isEmpty()) {
        if (keys_.isEmpty()) {
          keys_ = other.keys_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKeysIsMutable();
          keys_.addAll(other.keys_);
        }
        onChanged();
      }
      if (argsBuilder_ == null) {
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
      } else {
        if (!other.args_.isEmpty()) {
          if (argsBuilder_.isEmpty()) {
            argsBuilder_.dispose();
            argsBuilder_ = null;
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
            argsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                    getArgsFieldBuilder() : null;
          } else {
            argsBuilder_.addAllMessages(other.args_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      for (int i = 0; i < getArgsCount(); i++) {
        if (!getArgs(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbMapGetValuesRead parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbMapGetValuesRead) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.util.List<com.google.protobuf.ByteString> keys_ = java.util.Collections.emptyList();

    private void ensureKeysIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        keys_ = new java.util.ArrayList<com.google.protobuf.ByteString>(keys_);
        bitField0_ |= 0x00000001;
      }
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @return A list containing the keys.
     */
    public java.util.List<com.google.protobuf.ByteString>
    getKeysList() {
      return ((bitField0_ & 0x00000001) != 0) ?
          java.util.Collections.unmodifiableList(keys_) : keys_;
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @return The count of keys.
     */
    public int getKeysCount() {
      return keys_.size();
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The keys at the given index.
     */
    public com.google.protobuf.ByteString getKeys(int index) {
      return keys_.get(index);
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @param index The index to set the value at.
     * @param value The keys to set.
     * @return This builder for chaining.
     */
    public Builder setKeys(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureKeysIsMutable();
      keys_.set(index, value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @param value The keys to add.
     * @return This builder for chaining.
     */
    public Builder addKeys(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureKeysIsMutable();
      keys_.add(value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @param values The keys to add.
     * @return This builder for chaining.
     */
    public Builder addAllKeys(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keys_);
      onChanged();
      return this;
    }

    /**
     * <code>repeated bytes keys = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearKeys() {
      keys_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private java.util.List<com.arijo.protobuf.ApbMapEmbPartialArgs> args_ =
        java.util.Collections.emptyList();

    private void ensureArgsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        args_ = new java.util.ArrayList<com.arijo.protobuf.ApbMapEmbPartialArgs>(args_);
        bitField0_ |= 0x00000002;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.arijo.protobuf.ApbMapEmbPartialArgs, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder, com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder> argsBuilder_;

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public java.util.List<com.arijo.protobuf.ApbMapEmbPartialArgs> getArgsList() {
      if (argsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(args_);
      } else {
        return argsBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public int getArgsCount() {
      if (argsBuilder_ == null) {
        return args_.size();
      } else {
        return argsBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public com.arijo.protobuf.ApbMapEmbPartialArgs getArgs(int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);
      } else {
        return argsBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder setArgs(
        int index, com.arijo.protobuf.ApbMapEmbPartialArgs value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
      } else {
        argsBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder setArgs(
        int index, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.set(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder addArgs(com.arijo.protobuf.ApbMapEmbPartialArgs value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
      } else {
        argsBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder addArgs(
        int index, com.arijo.protobuf.ApbMapEmbPartialArgs value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(index, value);
        onChanged();
      } else {
        argsBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder addArgs(
        com.arijo.protobuf.ApbMapEmbPartialArgs.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder addArgs(
        int index, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends com.arijo.protobuf.ApbMapEmbPartialArgs> values) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
      } else {
        argsBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder clearArgs() {
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        argsBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public Builder removeArgs(int index) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.remove(index);
        onChanged();
      } else {
        argsBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public com.arijo.protobuf.ApbMapEmbPartialArgs.Builder getArgsBuilder(
        int index) {
      return getArgsFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder getArgsOrBuilder(
        int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);
      } else {
        return argsBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public java.util.List<? extends com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder>
    getArgsOrBuilderList() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(args_);
      }
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public com.arijo.protobuf.ApbMapEmbPartialArgs.Builder addArgsBuilder() {
      return getArgsFieldBuilder().addBuilder(
          com.arijo.protobuf.ApbMapEmbPartialArgs.getDefaultInstance());
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public com.arijo.protobuf.ApbMapEmbPartialArgs.Builder addArgsBuilder(
        int index) {
      return getArgsFieldBuilder().addBuilder(
          index, com.arijo.protobuf.ApbMapEmbPartialArgs.getDefaultInstance());
    }

    /**
     * <code>repeated .ApbMapEmbPartialArgs args = 2;</code>
     */
    public java.util.List<com.arijo.protobuf.ApbMapEmbPartialArgs.Builder>
    getArgsBuilderList() {
      return getArgsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.arijo.protobuf.ApbMapEmbPartialArgs, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder, com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder>
    getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.arijo.protobuf.ApbMapEmbPartialArgs, com.arijo.protobuf.ApbMapEmbPartialArgs.Builder, com.arijo.protobuf.ApbMapEmbPartialArgsOrBuilder>(
            args_,
            ((bitField0_ & 0x00000002) != 0),
            getParentForChildren(),
            isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbMapGetValuesRead)
  }

  // @@protoc_insertion_point(class_scope:ApbMapGetValuesRead)
  private static final com.arijo.protobuf.ApbMapGetValuesRead DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbMapGetValuesRead();
  }

  public static com.arijo.protobuf.ApbMapGetValuesRead getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbMapGetValuesRead>
      PARSER = new com.google.protobuf.AbstractParser<ApbMapGetValuesRead>() {
    @java.lang.Override
    public ApbMapGetValuesRead parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbMapGetValuesRead(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbMapGetValuesRead> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbMapGetValuesRead> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbMapGetValuesRead getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

