// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * Protobuf type {@code ApbPartialRead}
 */
public final class ApbPartialRead extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbPartialRead)
    ApbPartialReadOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbPartialRead.newBuilder() to construct.
  private ApbPartialRead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbPartialRead() {
    readtype_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbPartialRead();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbPartialRead(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.arijo.protobuf.ApbBoundObject.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = object_.toBuilder();
            }
            object_ = input.readMessage(com.arijo.protobuf.ApbBoundObject.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(object_);
              object_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            @SuppressWarnings("deprecation")
            com.arijo.protobuf.READ_type value = com.arijo.protobuf.READ_type.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              readtype_ = rawValue;
            }
            break;
          }
          case 26: {
            com.arijo.protobuf.ApbPartialReadArgs.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = args_.toBuilder();
            }
            args_ = input.readMessage(com.arijo.protobuf.ApbPartialReadArgs.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(args_);
              args_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbPartialRead_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbPartialRead_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbPartialRead.class, com.arijo.protobuf.ApbPartialRead.Builder.class);
  }

  private int bitField0_;
  public static final int OBJECT_FIELD_NUMBER = 1;
  private com.arijo.protobuf.ApbBoundObject object_;

  /**
   * <code>required .ApbBoundObject object = 1;</code>
   *
   * @return Whether the object field is set.
   */
  @java.lang.Override
  public boolean hasObject() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>required .ApbBoundObject object = 1;</code>
   *
   * @return The object.
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbBoundObject getObject() {
    return object_ == null ? com.arijo.protobuf.ApbBoundObject.getDefaultInstance() : object_;
  }

  /**
   * <code>required .ApbBoundObject object = 1;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbBoundObjectOrBuilder getObjectOrBuilder() {
    return object_ == null ? com.arijo.protobuf.ApbBoundObject.getDefaultInstance() : object_;
  }

  public static final int READTYPE_FIELD_NUMBER = 2;
  private int readtype_;

  /**
   * <code>required .READ_type readtype = 2;</code>
   *
   * @return Whether the readtype field is set.
   */
  @java.lang.Override
  public boolean hasReadtype() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>required .READ_type readtype = 2;</code>
   *
   * @return The readtype.
   */
  @java.lang.Override
  public com.arijo.protobuf.READ_type getReadtype() {
    @SuppressWarnings("deprecation")
    com.arijo.protobuf.READ_type result = com.arijo.protobuf.READ_type.valueOf(readtype_);
    return result == null ? com.arijo.protobuf.READ_type.FULL : result;
  }

  public static final int ARGS_FIELD_NUMBER = 3;
  private com.arijo.protobuf.ApbPartialReadArgs args_;

  /**
   * <code>required .ApbPartialReadArgs args = 3;</code>
   *
   * @return Whether the args field is set.
   */
  @java.lang.Override
  public boolean hasArgs() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <code>required .ApbPartialReadArgs args = 3;</code>
   *
   * @return The args.
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbPartialReadArgs getArgs() {
    return args_ == null ? com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
  }

  /**
   * <code>required .ApbPartialReadArgs args = 3;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbPartialReadArgsOrBuilder getArgsOrBuilder() {
    return args_ == null ? com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasObject()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasReadtype()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasArgs()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getObject().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getArgs().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getObject());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, readtype_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getArgs());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getObject());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, readtype_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getArgs());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbPartialRead)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbPartialRead other = (com.arijo.protobuf.ApbPartialRead) obj;

    if (hasObject() != other.hasObject()) return false;
    if (hasObject()) {
      if (!getObject()
          .equals(other.getObject())) return false;
    }
    if (hasReadtype() != other.hasReadtype()) return false;
    if (hasReadtype()) {
      if (readtype_ != other.readtype_) return false;
    }
    if (hasArgs() != other.hasArgs()) return false;
    if (hasArgs()) {
      if (!getArgs()
          .equals(other.getArgs())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasObject()) {
      hash = (37 * hash) + OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getObject().hashCode();
    }
    if (hasReadtype()) {
      hash = (37 * hash) + READTYPE_FIELD_NUMBER;
      hash = (53 * hash) + readtype_;
    }
    if (hasArgs()) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgs().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbPartialRead parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbPartialRead parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbPartialRead parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbPartialRead prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code ApbPartialRead}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbPartialRead)
      com.arijo.protobuf.ApbPartialReadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbPartialRead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbPartialRead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbPartialRead.class, com.arijo.protobuf.ApbPartialRead.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbPartialRead.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getObjectFieldBuilder();
        getArgsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (objectBuilder_ == null) {
        object_ = null;
      } else {
        objectBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      readtype_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (argsBuilder_ == null) {
        args_ = null;
      } else {
        argsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbPartialRead_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbPartialRead getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbPartialRead.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbPartialRead build() {
      com.arijo.protobuf.ApbPartialRead result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbPartialRead buildPartial() {
      com.arijo.protobuf.ApbPartialRead result = new com.arijo.protobuf.ApbPartialRead(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (objectBuilder_ == null) {
          result.object_ = object_;
        } else {
          result.object_ = objectBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.readtype_ = readtype_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (argsBuilder_ == null) {
          result.args_ = args_;
        } else {
          result.args_ = argsBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbPartialRead) {
        return mergeFrom((com.arijo.protobuf.ApbPartialRead) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbPartialRead other) {
      if (other == com.arijo.protobuf.ApbPartialRead.getDefaultInstance()) return this;
      if (other.hasObject()) {
        mergeObject(other.getObject());
      }
      if (other.hasReadtype()) {
        setReadtype(other.getReadtype());
      }
      if (other.hasArgs()) {
        mergeArgs(other.getArgs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasObject()) {
        return false;
      }
      if (!hasReadtype()) {
        return false;
      }
      if (!hasArgs()) {
        return false;
      }
      if (!getObject().isInitialized()) {
        return false;
      }
      if (!getArgs().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbPartialRead parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbPartialRead) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.arijo.protobuf.ApbBoundObject object_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbBoundObject, com.arijo.protobuf.ApbBoundObject.Builder, com.arijo.protobuf.ApbBoundObjectOrBuilder> objectBuilder_;

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     *
     * @return Whether the object field is set.
     */
    public boolean hasObject() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     *
     * @return The object.
     */
    public com.arijo.protobuf.ApbBoundObject getObject() {
      if (objectBuilder_ == null) {
        return object_ == null ? com.arijo.protobuf.ApbBoundObject.getDefaultInstance() : object_;
      } else {
        return objectBuilder_.getMessage();
      }
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    public Builder setObject(com.arijo.protobuf.ApbBoundObject value) {
      if (objectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        object_ = value;
        onChanged();
      } else {
        objectBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    public Builder setObject(
        com.arijo.protobuf.ApbBoundObject.Builder builderForValue) {
      if (objectBuilder_ == null) {
        object_ = builderForValue.build();
        onChanged();
      } else {
        objectBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    public Builder mergeObject(com.arijo.protobuf.ApbBoundObject value) {
      if (objectBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            object_ != null &&
            object_ != com.arijo.protobuf.ApbBoundObject.getDefaultInstance()) {
          object_ =
              com.arijo.protobuf.ApbBoundObject.newBuilder(object_).mergeFrom(value).buildPartial();
        } else {
          object_ = value;
        }
        onChanged();
      } else {
        objectBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    public Builder clearObject() {
      if (objectBuilder_ == null) {
        object_ = null;
        onChanged();
      } else {
        objectBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    public com.arijo.protobuf.ApbBoundObject.Builder getObjectBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getObjectFieldBuilder().getBuilder();
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    public com.arijo.protobuf.ApbBoundObjectOrBuilder getObjectOrBuilder() {
      if (objectBuilder_ != null) {
        return objectBuilder_.getMessageOrBuilder();
      } else {
        return object_ == null ?
            com.arijo.protobuf.ApbBoundObject.getDefaultInstance() : object_;
      }
    }

    /**
     * <code>required .ApbBoundObject object = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbBoundObject, com.arijo.protobuf.ApbBoundObject.Builder, com.arijo.protobuf.ApbBoundObjectOrBuilder>
    getObjectFieldBuilder() {
      if (objectBuilder_ == null) {
        objectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.arijo.protobuf.ApbBoundObject, com.arijo.protobuf.ApbBoundObject.Builder, com.arijo.protobuf.ApbBoundObjectOrBuilder>(
            getObject(),
            getParentForChildren(),
            isClean());
        object_ = null;
      }
      return objectBuilder_;
    }

    private int readtype_ = 0;

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @return Whether the readtype field is set.
     */
    @java.lang.Override
    public boolean hasReadtype() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @return The readtype.
     */
    @java.lang.Override
    public com.arijo.protobuf.READ_type getReadtype() {
      @SuppressWarnings("deprecation")
      com.arijo.protobuf.READ_type result = com.arijo.protobuf.READ_type.valueOf(readtype_);
      return result == null ? com.arijo.protobuf.READ_type.FULL : result;
    }

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @param value The readtype to set.
     * @return This builder for chaining.
     */
    public Builder setReadtype(com.arijo.protobuf.READ_type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      readtype_ = value.getNumber();
      onChanged();
      return this;
    }

    /**
     * <code>required .READ_type readtype = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearReadtype() {
      bitField0_ = (bitField0_ & ~0x00000002);
      readtype_ = 0;
      onChanged();
      return this;
    }

    private com.arijo.protobuf.ApbPartialReadArgs args_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbPartialReadArgs, com.arijo.protobuf.ApbPartialReadArgs.Builder, com.arijo.protobuf.ApbPartialReadArgsOrBuilder> argsBuilder_;

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     *
     * @return Whether the args field is set.
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     *
     * @return The args.
     */
    public com.arijo.protobuf.ApbPartialReadArgs getArgs() {
      if (argsBuilder_ == null) {
        return args_ == null ? com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
      } else {
        return argsBuilder_.getMessage();
      }
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    public Builder setArgs(com.arijo.protobuf.ApbPartialReadArgs value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        args_ = value;
        onChanged();
      } else {
        argsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    public Builder setArgs(
        com.arijo.protobuf.ApbPartialReadArgs.Builder builderForValue) {
      if (argsBuilder_ == null) {
        args_ = builderForValue.build();
        onChanged();
      } else {
        argsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    public Builder mergeArgs(com.arijo.protobuf.ApbPartialReadArgs value) {
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            args_ != null &&
            args_ != com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance()) {
          args_ =
              com.arijo.protobuf.ApbPartialReadArgs.newBuilder(args_).mergeFrom(value).buildPartial();
        } else {
          args_ = value;
        }
        onChanged();
      } else {
        argsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    public Builder clearArgs() {
      if (argsBuilder_ == null) {
        args_ = null;
        onChanged();
      } else {
        argsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    public com.arijo.protobuf.ApbPartialReadArgs.Builder getArgsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getArgsFieldBuilder().getBuilder();
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    public com.arijo.protobuf.ApbPartialReadArgsOrBuilder getArgsOrBuilder() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilder();
      } else {
        return args_ == null ?
            com.arijo.protobuf.ApbPartialReadArgs.getDefaultInstance() : args_;
      }
    }

    /**
     * <code>required .ApbPartialReadArgs args = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbPartialReadArgs, com.arijo.protobuf.ApbPartialReadArgs.Builder, com.arijo.protobuf.ApbPartialReadArgsOrBuilder>
    getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.arijo.protobuf.ApbPartialReadArgs, com.arijo.protobuf.ApbPartialReadArgs.Builder, com.arijo.protobuf.ApbPartialReadArgsOrBuilder>(
            getArgs(),
            getParentForChildren(),
            isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbPartialRead)
  }

  // @@protoc_insertion_point(class_scope:ApbPartialRead)
  private static final com.arijo.protobuf.ApbPartialRead DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbPartialRead();
  }

  public static com.arijo.protobuf.ApbPartialRead getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbPartialRead>
      PARSER = new com.google.protobuf.AbstractParser<ApbPartialRead>() {
    @java.lang.Override
    public ApbPartialRead parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbPartialRead(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbPartialRead> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbPartialRead> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbPartialRead getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

