// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbRegUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbRegUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bytes value = 1;</code>
   *
   * @return Whether the value field is set.
   */
  boolean hasValue();

  /**
   * <code>required bytes value = 1;</code>
   *
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
