// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbReadObjectsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbReadObjects)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ApbBoundObject boundobjects = 1;</code>
   */
  java.util.List<com.arijo.protobuf.ApbBoundObject>
  getBoundobjectsList();

  /**
   * <code>repeated .ApbBoundObject boundobjects = 1;</code>
   */
  com.arijo.protobuf.ApbBoundObject getBoundobjects(int index);

  /**
   * <code>repeated .ApbBoundObject boundobjects = 1;</code>
   */
  int getBoundobjectsCount();

  /**
   * <code>repeated .ApbBoundObject boundobjects = 1;</code>
   */
  java.util.List<? extends com.arijo.protobuf.ApbBoundObjectOrBuilder>
  getBoundobjectsOrBuilderList();

  /**
   * <code>repeated .ApbBoundObject boundobjects = 1;</code>
   */
  com.arijo.protobuf.ApbBoundObjectOrBuilder getBoundobjectsOrBuilder(
      int index);

  /**
   * <code>required bytes transaction_descriptor = 2;</code>
   *
   * @return Whether the transactionDescriptor field is set.
   */
  boolean hasTransactionDescriptor();

  /**
   * <code>required bytes transaction_descriptor = 2;</code>
   *
   * @return The transactionDescriptor.
   */
  com.google.protobuf.ByteString getTransactionDescriptor();
}
