// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbReadObjectRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbReadObjectResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * one of the following:
   * </pre>
   *
   * <code>optional .ApbGetCounterResp counter = 1;</code>
   *
   * @return Whether the counter field is set.
   */
  boolean hasCounter();

  /**
   * <pre>
   * one of the following:
   * </pre>
   *
   * <code>optional .ApbGetCounterResp counter = 1;</code>
   *
   * @return The counter.
   */
  com.arijo.protobuf.ApbGetCounterResp getCounter();

  /**
   * <pre>
   * one of the following:
   * </pre>
   *
   * <code>optional .ApbGetCounterResp counter = 1;</code>
   */
  com.arijo.protobuf.ApbGetCounterRespOrBuilder getCounterOrBuilder();

  /**
   * <code>optional .ApbGetSetResp set = 2;</code>
   *
   * @return Whether the set field is set.
   */
  boolean hasSet();

  /**
   * <code>optional .ApbGetSetResp set = 2;</code>
   *
   * @return The set.
   */
  com.arijo.protobuf.ApbGetSetResp getSet();

  /**
   * <code>optional .ApbGetSetResp set = 2;</code>
   */
  com.arijo.protobuf.ApbGetSetRespOrBuilder getSetOrBuilder();

  /**
   * <code>optional .ApbGetRegResp reg = 3;</code>
   *
   * @return Whether the reg field is set.
   */
  boolean hasReg();

  /**
   * <code>optional .ApbGetRegResp reg = 3;</code>
   *
   * @return The reg.
   */
  com.arijo.protobuf.ApbGetRegResp getReg();

  /**
   * <code>optional .ApbGetRegResp reg = 3;</code>
   */
  com.arijo.protobuf.ApbGetRegRespOrBuilder getRegOrBuilder();

  /**
   * <code>optional .ApbGetMVRegResp mvreg = 4;</code>
   *
   * @return Whether the mvreg field is set.
   */
  boolean hasMvreg();

  /**
   * <code>optional .ApbGetMVRegResp mvreg = 4;</code>
   *
   * @return The mvreg.
   */
  com.arijo.protobuf.ApbGetMVRegResp getMvreg();

  /**
   * <code>optional .ApbGetMVRegResp mvreg = 4;</code>
   */
  com.arijo.protobuf.ApbGetMVRegRespOrBuilder getMvregOrBuilder();

  /**
   * <code>optional .ApbGetMapResp map = 6;</code>
   *
   * @return Whether the map field is set.
   */
  boolean hasMap();

  /**
   * <code>optional .ApbGetMapResp map = 6;</code>
   *
   * @return The map.
   */
  com.arijo.protobuf.ApbGetMapResp getMap();

  /**
   * <code>optional .ApbGetMapResp map = 6;</code>
   */
  com.arijo.protobuf.ApbGetMapRespOrBuilder getMapOrBuilder();

  /**
   * <code>optional .ApbGetFlagResp flag = 7;</code>
   *
   * @return Whether the flag field is set.
   */
  boolean hasFlag();

  /**
   * <code>optional .ApbGetFlagResp flag = 7;</code>
   *
   * @return The flag.
   */
  com.arijo.protobuf.ApbGetFlagResp getFlag();

  /**
   * <code>optional .ApbGetFlagResp flag = 7;</code>
   */
  com.arijo.protobuf.ApbGetFlagRespOrBuilder getFlagOrBuilder();

  /**
   * <code>optional .ApbGetMaxMinResp maxmin = 12;</code>
   *
   * @return Whether the maxmin field is set.
   */
  boolean hasMaxmin();

  /**
   * <code>optional .ApbGetMaxMinResp maxmin = 12;</code>
   *
   * @return The maxmin.
   */
  com.arijo.protobuf.ApbGetMaxMinResp getMaxmin();

  /**
   * <code>optional .ApbGetMaxMinResp maxmin = 12;</code>
   */
  com.arijo.protobuf.ApbGetMaxMinRespOrBuilder getMaxminOrBuilder();

  /**
   * <pre>
   * Also used for TopSum
   * </pre>
   *
   * <code>optional .ApbGetTopkResp topk = 13;</code>
   *
   * @return Whether the topk field is set.
   */
  boolean hasTopk();

  /**
   * <pre>
   * Also used for TopSum
   * </pre>
   *
   * <code>optional .ApbGetTopkResp topk = 13;</code>
   *
   * @return The topk.
   */
  com.arijo.protobuf.ApbGetTopkResp getTopk();

  /**
   * <pre>
   * Also used for TopSum
   * </pre>
   *
   * <code>optional .ApbGetTopkResp topk = 13;</code>
   */
  com.arijo.protobuf.ApbGetTopkRespOrBuilder getTopkOrBuilder();

  /**
   * <code>optional .ApbGetLeaderboardResp leadb = 14;</code>
   *
   * @return Whether the leadb field is set.
   */
  boolean hasLeadb();

  /**
   * <code>optional .ApbGetLeaderboardResp leadb = 14;</code>
   *
   * @return The leadb.
   */
  com.arijo.protobuf.ApbGetLeaderboardResp getLeadb();

  /**
   * <code>optional .ApbGetLeaderboardResp leadb = 14;</code>
   */
  com.arijo.protobuf.ApbGetLeaderboardRespOrBuilder getLeadbOrBuilder();

  /**
   * <code>optional .ApbGetAverageResp avg = 15;</code>
   *
   * @return Whether the avg field is set.
   */
  boolean hasAvg();

  /**
   * <code>optional .ApbGetAverageResp avg = 15;</code>
   *
   * @return The avg.
   */
  com.arijo.protobuf.ApbGetAverageResp getAvg();

  /**
   * <code>optional .ApbGetAverageResp avg = 15;</code>
   */
  com.arijo.protobuf.ApbGetAverageRespOrBuilder getAvgOrBuilder();

  /**
   * <pre>
   * Generic for non-full state reads from any CRDT
   * </pre>
   *
   * <code>optional .ApbPartialReadResp partread = 8;</code>
   *
   * @return Whether the partread field is set.
   */
  boolean hasPartread();

  /**
   * <pre>
   * Generic for non-full state reads from any CRDT
   * </pre>
   *
   * <code>optional .ApbPartialReadResp partread = 8;</code>
   *
   * @return The partread.
   */
  com.arijo.protobuf.ApbPartialReadResp getPartread();

  /**
   * <pre>
   * Generic for non-full state reads from any CRDT
   * </pre>
   *
   * <code>optional .ApbPartialReadResp partread = 8;</code>
   */
  com.arijo.protobuf.ApbPartialReadRespOrBuilder getPartreadOrBuilder();
}
