// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbStartTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbStartTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes timestamp = 1;</code>
   *
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();

  /**
   * <code>optional bytes timestamp = 1;</code>
   *
   * @return The timestamp.
   */
  com.google.protobuf.ByteString getTimestamp();

  /**
   * <code>optional .ApbTxnProperties properties = 2;</code>
   *
   * @return Whether the properties field is set.
   */
  boolean hasProperties();

  /**
   * <code>optional .ApbTxnProperties properties = 2;</code>
   *
   * @return The properties.
   */
  com.arijo.protobuf.ApbTxnProperties getProperties();

  /**
   * <code>optional .ApbTxnProperties properties = 2;</code>
   */
  com.arijo.protobuf.ApbTxnPropertiesOrBuilder getPropertiesOrBuilder();
}
