// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbSetPartialReadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbSetPartialRead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ApbSetLookupRead lookup = 1;</code>
   *
   * @return Whether the lookup field is set.
   */
  boolean hasLookup();

  /**
   * <code>optional .ApbSetLookupRead lookup = 1;</code>
   *
   * @return The lookup.
   */
  com.arijo.protobuf.ApbSetLookupRead getLookup();

  /**
   * <code>optional .ApbSetLookupRead lookup = 1;</code>
   */
  com.arijo.protobuf.ApbSetLookupReadOrBuilder getLookupOrBuilder();
}
