// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbStaticReadObjectsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbStaticReadObjectsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ApbReadObjectsResp objects = 1;</code>
   *
   * @return Whether the objects field is set.
   */
  boolean hasObjects();

  /**
   * <code>required .ApbReadObjectsResp objects = 1;</code>
   *
   * @return The objects.
   */
  com.arijo.protobuf.ApbReadObjectsResp getObjects();

  /**
   * <code>required .ApbReadObjectsResp objects = 1;</code>
   */
  com.arijo.protobuf.ApbReadObjectsRespOrBuilder getObjectsOrBuilder();

  /**
   * <code>required .ApbCommitResp committime = 2;</code>
   *
   * @return Whether the committime field is set.
   */
  boolean hasCommittime();

  /**
   * <code>required .ApbCommitResp committime = 2;</code>
   *
   * @return The committime.
   */
  com.arijo.protobuf.ApbCommitResp getCommittime();

  /**
   * <code>required .ApbCommitResp committime = 2;</code>
   */
  com.arijo.protobuf.ApbCommitRespOrBuilder getCommittimeOrBuilder();
}
