// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbStaticUpdateObjectsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbStaticUpdateObjects)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .ApbStartTransaction transaction = 1;</code>
   *
   * @return Whether the transaction field is set.
   */
  boolean hasTransaction();

  /**
   * <code>required .ApbStartTransaction transaction = 1;</code>
   *
   * @return The transaction.
   */
  com.arijo.protobuf.ApbStartTransaction getTransaction();

  /**
   * <code>required .ApbStartTransaction transaction = 1;</code>
   */
  com.arijo.protobuf.ApbStartTransactionOrBuilder getTransactionOrBuilder();

  /**
   * <code>repeated .ApbUpdateOp updates = 2;</code>
   */
  java.util.List<com.arijo.protobuf.ApbUpdateOp>
  getUpdatesList();

  /**
   * <code>repeated .ApbUpdateOp updates = 2;</code>
   */
  com.arijo.protobuf.ApbUpdateOp getUpdates(int index);

  /**
   * <code>repeated .ApbUpdateOp updates = 2;</code>
   */
  int getUpdatesCount();

  /**
   * <code>repeated .ApbUpdateOp updates = 2;</code>
   */
  java.util.List<? extends com.arijo.protobuf.ApbUpdateOpOrBuilder>
  getUpdatesOrBuilderList();

  /**
   * <code>repeated .ApbUpdateOp updates = 2;</code>
   */
  com.arijo.protobuf.ApbUpdateOpOrBuilder getUpdatesOrBuilder(
      int index);
}
