// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * Protobuf type {@code ApbTopkPartialRead}
 */
public final class ApbTopkPartialRead extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbTopkPartialRead)
    ApbTopkPartialReadOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbTopkPartialRead.newBuilder() to construct.
  private ApbTopkPartialRead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbTopkPartialRead() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbTopkPartialRead();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbTopkPartialRead(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.arijo.protobuf.ApbTopkGetNRead.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = getn_.toBuilder();
            }
            getn_ = input.readMessage(com.arijo.protobuf.ApbTopkGetNRead.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(getn_);
              getn_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.arijo.protobuf.ApbTopkAboveValueRead.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = getabovevalue_.toBuilder();
            }
            getabovevalue_ = input.readMessage(com.arijo.protobuf.ApbTopkAboveValueRead.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(getabovevalue_);
              getabovevalue_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbTopkPartialRead_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbTopkPartialRead_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbTopkPartialRead.class, com.arijo.protobuf.ApbTopkPartialRead.Builder.class);
  }

  private int bitField0_;
  public static final int GETN_FIELD_NUMBER = 1;
  private com.arijo.protobuf.ApbTopkGetNRead getn_;

  /**
   * <code>optional .ApbTopkGetNRead getn = 1;</code>
   *
   * @return Whether the getn field is set.
   */
  @java.lang.Override
  public boolean hasGetn() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>optional .ApbTopkGetNRead getn = 1;</code>
   *
   * @return The getn.
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbTopkGetNRead getGetn() {
    return getn_ == null ? com.arijo.protobuf.ApbTopkGetNRead.getDefaultInstance() : getn_;
  }

  /**
   * <code>optional .ApbTopkGetNRead getn = 1;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbTopkGetNReadOrBuilder getGetnOrBuilder() {
    return getn_ == null ? com.arijo.protobuf.ApbTopkGetNRead.getDefaultInstance() : getn_;
  }

  public static final int GETABOVEVALUE_FIELD_NUMBER = 2;
  private com.arijo.protobuf.ApbTopkAboveValueRead getabovevalue_;

  /**
   * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
   *
   * @return Whether the getabovevalue field is set.
   */
  @java.lang.Override
  public boolean hasGetabovevalue() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
   *
   * @return The getabovevalue.
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbTopkAboveValueRead getGetabovevalue() {
    return getabovevalue_ == null ? com.arijo.protobuf.ApbTopkAboveValueRead.getDefaultInstance() : getabovevalue_;
  }

  /**
   * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
   */
  @java.lang.Override
  public com.arijo.protobuf.ApbTopkAboveValueReadOrBuilder getGetabovevalueOrBuilder() {
    return getabovevalue_ == null ? com.arijo.protobuf.ApbTopkAboveValueRead.getDefaultInstance() : getabovevalue_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasGetn()) {
      if (!getGetn().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasGetabovevalue()) {
      if (!getGetabovevalue().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGetn());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getGetabovevalue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGetn());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGetabovevalue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbTopkPartialRead)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbTopkPartialRead other = (com.arijo.protobuf.ApbTopkPartialRead) obj;

    if (hasGetn() != other.hasGetn()) return false;
    if (hasGetn()) {
      if (!getGetn()
          .equals(other.getGetn())) return false;
    }
    if (hasGetabovevalue() != other.hasGetabovevalue()) return false;
    if (hasGetabovevalue()) {
      if (!getGetabovevalue()
          .equals(other.getGetabovevalue())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGetn()) {
      hash = (37 * hash) + GETN_FIELD_NUMBER;
      hash = (53 * hash) + getGetn().hashCode();
    }
    if (hasGetabovevalue()) {
      hash = (37 * hash) + GETABOVEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getGetabovevalue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbTopkPartialRead parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbTopkPartialRead prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code ApbTopkPartialRead}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbTopkPartialRead)
      com.arijo.protobuf.ApbTopkPartialReadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbTopkPartialRead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbTopkPartialRead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbTopkPartialRead.class, com.arijo.protobuf.ApbTopkPartialRead.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbTopkPartialRead.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        getGetnFieldBuilder();
        getGetabovevalueFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (getnBuilder_ == null) {
        getn_ = null;
      } else {
        getnBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (getabovevalueBuilder_ == null) {
        getabovevalue_ = null;
      } else {
        getabovevalueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbTopkPartialRead_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbTopkPartialRead getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbTopkPartialRead.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbTopkPartialRead build() {
      com.arijo.protobuf.ApbTopkPartialRead result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbTopkPartialRead buildPartial() {
      com.arijo.protobuf.ApbTopkPartialRead result = new com.arijo.protobuf.ApbTopkPartialRead(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (getnBuilder_ == null) {
          result.getn_ = getn_;
        } else {
          result.getn_ = getnBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (getabovevalueBuilder_ == null) {
          result.getabovevalue_ = getabovevalue_;
        } else {
          result.getabovevalue_ = getabovevalueBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbTopkPartialRead) {
        return mergeFrom((com.arijo.protobuf.ApbTopkPartialRead) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbTopkPartialRead other) {
      if (other == com.arijo.protobuf.ApbTopkPartialRead.getDefaultInstance()) return this;
      if (other.hasGetn()) {
        mergeGetn(other.getGetn());
      }
      if (other.hasGetabovevalue()) {
        mergeGetabovevalue(other.getGetabovevalue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (hasGetn()) {
        if (!getGetn().isInitialized()) {
          return false;
        }
      }
      if (hasGetabovevalue()) {
        if (!getGetabovevalue().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbTopkPartialRead parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbTopkPartialRead) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.arijo.protobuf.ApbTopkGetNRead getn_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbTopkGetNRead, com.arijo.protobuf.ApbTopkGetNRead.Builder, com.arijo.protobuf.ApbTopkGetNReadOrBuilder> getnBuilder_;

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     *
     * @return Whether the getn field is set.
     */
    public boolean hasGetn() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     *
     * @return The getn.
     */
    public com.arijo.protobuf.ApbTopkGetNRead getGetn() {
      if (getnBuilder_ == null) {
        return getn_ == null ? com.arijo.protobuf.ApbTopkGetNRead.getDefaultInstance() : getn_;
      } else {
        return getnBuilder_.getMessage();
      }
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    public Builder setGetn(com.arijo.protobuf.ApbTopkGetNRead value) {
      if (getnBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        getn_ = value;
        onChanged();
      } else {
        getnBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    public Builder setGetn(
        com.arijo.protobuf.ApbTopkGetNRead.Builder builderForValue) {
      if (getnBuilder_ == null) {
        getn_ = builderForValue.build();
        onChanged();
      } else {
        getnBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    public Builder mergeGetn(com.arijo.protobuf.ApbTopkGetNRead value) {
      if (getnBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            getn_ != null &&
            getn_ != com.arijo.protobuf.ApbTopkGetNRead.getDefaultInstance()) {
          getn_ =
              com.arijo.protobuf.ApbTopkGetNRead.newBuilder(getn_).mergeFrom(value).buildPartial();
        } else {
          getn_ = value;
        }
        onChanged();
      } else {
        getnBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    public Builder clearGetn() {
      if (getnBuilder_ == null) {
        getn_ = null;
        onChanged();
      } else {
        getnBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    public com.arijo.protobuf.ApbTopkGetNRead.Builder getGetnBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGetnFieldBuilder().getBuilder();
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    public com.arijo.protobuf.ApbTopkGetNReadOrBuilder getGetnOrBuilder() {
      if (getnBuilder_ != null) {
        return getnBuilder_.getMessageOrBuilder();
      } else {
        return getn_ == null ?
            com.arijo.protobuf.ApbTopkGetNRead.getDefaultInstance() : getn_;
      }
    }

    /**
     * <code>optional .ApbTopkGetNRead getn = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbTopkGetNRead, com.arijo.protobuf.ApbTopkGetNRead.Builder, com.arijo.protobuf.ApbTopkGetNReadOrBuilder>
    getGetnFieldBuilder() {
      if (getnBuilder_ == null) {
        getnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.arijo.protobuf.ApbTopkGetNRead, com.arijo.protobuf.ApbTopkGetNRead.Builder, com.arijo.protobuf.ApbTopkGetNReadOrBuilder>(
            getGetn(),
            getParentForChildren(),
            isClean());
        getn_ = null;
      }
      return getnBuilder_;
    }

    private com.arijo.protobuf.ApbTopkAboveValueRead getabovevalue_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbTopkAboveValueRead, com.arijo.protobuf.ApbTopkAboveValueRead.Builder, com.arijo.protobuf.ApbTopkAboveValueReadOrBuilder> getabovevalueBuilder_;

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     *
     * @return Whether the getabovevalue field is set.
     */
    public boolean hasGetabovevalue() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     *
     * @return The getabovevalue.
     */
    public com.arijo.protobuf.ApbTopkAboveValueRead getGetabovevalue() {
      if (getabovevalueBuilder_ == null) {
        return getabovevalue_ == null ? com.arijo.protobuf.ApbTopkAboveValueRead.getDefaultInstance() : getabovevalue_;
      } else {
        return getabovevalueBuilder_.getMessage();
      }
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    public Builder setGetabovevalue(com.arijo.protobuf.ApbTopkAboveValueRead value) {
      if (getabovevalueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        getabovevalue_ = value;
        onChanged();
      } else {
        getabovevalueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    public Builder setGetabovevalue(
        com.arijo.protobuf.ApbTopkAboveValueRead.Builder builderForValue) {
      if (getabovevalueBuilder_ == null) {
        getabovevalue_ = builderForValue.build();
        onChanged();
      } else {
        getabovevalueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    public Builder mergeGetabovevalue(com.arijo.protobuf.ApbTopkAboveValueRead value) {
      if (getabovevalueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            getabovevalue_ != null &&
            getabovevalue_ != com.arijo.protobuf.ApbTopkAboveValueRead.getDefaultInstance()) {
          getabovevalue_ =
              com.arijo.protobuf.ApbTopkAboveValueRead.newBuilder(getabovevalue_).mergeFrom(value).buildPartial();
        } else {
          getabovevalue_ = value;
        }
        onChanged();
      } else {
        getabovevalueBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    public Builder clearGetabovevalue() {
      if (getabovevalueBuilder_ == null) {
        getabovevalue_ = null;
        onChanged();
      } else {
        getabovevalueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    public com.arijo.protobuf.ApbTopkAboveValueRead.Builder getGetabovevalueBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getGetabovevalueFieldBuilder().getBuilder();
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    public com.arijo.protobuf.ApbTopkAboveValueReadOrBuilder getGetabovevalueOrBuilder() {
      if (getabovevalueBuilder_ != null) {
        return getabovevalueBuilder_.getMessageOrBuilder();
      } else {
        return getabovevalue_ == null ?
            com.arijo.protobuf.ApbTopkAboveValueRead.getDefaultInstance() : getabovevalue_;
      }
    }

    /**
     * <code>optional .ApbTopkAboveValueRead getabovevalue = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.arijo.protobuf.ApbTopkAboveValueRead, com.arijo.protobuf.ApbTopkAboveValueRead.Builder, com.arijo.protobuf.ApbTopkAboveValueReadOrBuilder>
    getGetabovevalueFieldBuilder() {
      if (getabovevalueBuilder_ == null) {
        getabovevalueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.arijo.protobuf.ApbTopkAboveValueRead, com.arijo.protobuf.ApbTopkAboveValueRead.Builder, com.arijo.protobuf.ApbTopkAboveValueReadOrBuilder>(
            getGetabovevalue(),
            getParentForChildren(),
            isClean());
        getabovevalue_ = null;
      }
      return getabovevalueBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbTopkPartialRead)
  }

  // @@protoc_insertion_point(class_scope:ApbTopkPartialRead)
  private static final com.arijo.protobuf.ApbTopkPartialRead DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbTopkPartialRead();
  }

  public static com.arijo.protobuf.ApbTopkPartialRead getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbTopkPartialRead>
      PARSER = new com.google.protobuf.AbstractParser<ApbTopkPartialRead>() {
    @java.lang.Override
    public ApbTopkPartialRead parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbTopkPartialRead(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbTopkPartialRead> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbTopkPartialRead> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbTopkPartialRead getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

