// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * <pre>
 * Properties parameters of a transaction
 * </pre>
 * <p>
 * Protobuf type {@code ApbTxnProperties}
 */
public final class ApbTxnProperties extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ApbTxnProperties)
    ApbTxnPropertiesOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use ApbTxnProperties.newBuilder() to construct.
  private ApbTxnProperties(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ApbTxnProperties() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApbTxnProperties();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private ApbTxnProperties(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            readWrite_ = input.readUInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            redBlue_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbTxnProperties_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.arijo.protobuf.AntidotePB.internal_static_ApbTxnProperties_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arijo.protobuf.ApbTxnProperties.class, com.arijo.protobuf.ApbTxnProperties.Builder.class);
  }

  private int bitField0_;
  public static final int READ_WRITE_FIELD_NUMBER = 1;
  private int readWrite_;

  /**
   * <pre>
   * default = 0 = read_write, 1 = read_only, 2 = write_only
   * </pre>
   *
   * <code>optional uint32 read_write = 1;</code>
   *
   * @return Whether the readWrite field is set.
   */
  @java.lang.Override
  public boolean hasReadWrite() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <pre>
   * default = 0 = read_write, 1 = read_only, 2 = write_only
   * </pre>
   *
   * <code>optional uint32 read_write = 1;</code>
   *
   * @return The readWrite.
   */
  @java.lang.Override
  public int getReadWrite() {
    return readWrite_;
  }

  public static final int RED_BLUE_FIELD_NUMBER = 2;
  private int redBlue_;

  /**
   * <pre>
   * default = 0 = blue, 1 = red
   * </pre>
   *
   * <code>optional uint32 red_blue = 2;</code>
   *
   * @return Whether the redBlue field is set.
   */
  @java.lang.Override
  public boolean hasRedBlue() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <pre>
   * default = 0 = blue, 1 = red
   * </pre>
   *
   * <code>optional uint32 red_blue = 2;</code>
   *
   * @return The redBlue.
   */
  @java.lang.Override
  public int getRedBlue() {
    return redBlue_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt32(1, readWrite_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeUInt32(2, redBlue_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, readWrite_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, redBlue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.arijo.protobuf.ApbTxnProperties)) {
      return super.equals(obj);
    }
    com.arijo.protobuf.ApbTxnProperties other = (com.arijo.protobuf.ApbTxnProperties) obj;

    if (hasReadWrite() != other.hasReadWrite()) return false;
    if (hasReadWrite()) {
      if (getReadWrite()
          != other.getReadWrite()) return false;
    }
    if (hasRedBlue() != other.hasRedBlue()) return false;
    if (hasRedBlue()) {
      if (getRedBlue()
          != other.getRedBlue()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReadWrite()) {
      hash = (37 * hash) + READ_WRITE_FIELD_NUMBER;
      hash = (53 * hash) + getReadWrite();
    }
    if (hasRedBlue()) {
      hash = (37 * hash) + RED_BLUE_FIELD_NUMBER;
      hash = (53 * hash) + getRedBlue();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static com.arijo.protobuf.ApbTxnProperties parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.arijo.protobuf.ApbTxnProperties prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * Properties parameters of a transaction
   * </pre>
   * <p>
   * Protobuf type {@code ApbTxnProperties}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ApbTxnProperties)
      com.arijo.protobuf.ApbTxnPropertiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbTxnProperties_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbTxnProperties_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arijo.protobuf.ApbTxnProperties.class, com.arijo.protobuf.ApbTxnProperties.Builder.class);
    }

    // Construct using com.arijo.protobuf.ApbTxnProperties.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      readWrite_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      redBlue_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.arijo.protobuf.AntidotePB.internal_static_ApbTxnProperties_descriptor;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbTxnProperties getDefaultInstanceForType() {
      return com.arijo.protobuf.ApbTxnProperties.getDefaultInstance();
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbTxnProperties build() {
      com.arijo.protobuf.ApbTxnProperties result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arijo.protobuf.ApbTxnProperties buildPartial() {
      com.arijo.protobuf.ApbTxnProperties result = new com.arijo.protobuf.ApbTxnProperties(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.readWrite_ = readWrite_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.redBlue_ = redBlue_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arijo.protobuf.ApbTxnProperties) {
        return mergeFrom((com.arijo.protobuf.ApbTxnProperties) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arijo.protobuf.ApbTxnProperties other) {
      if (other == com.arijo.protobuf.ApbTxnProperties.getDefaultInstance()) return this;
      if (other.hasReadWrite()) {
        setReadWrite(other.getReadWrite());
      }
      if (other.hasRedBlue()) {
        setRedBlue(other.getRedBlue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.arijo.protobuf.ApbTxnProperties parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.arijo.protobuf.ApbTxnProperties) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private int readWrite_;

    /**
     * <pre>
     * default = 0 = read_write, 1 = read_only, 2 = write_only
     * </pre>
     *
     * <code>optional uint32 read_write = 1;</code>
     *
     * @return Whether the readWrite field is set.
     */
    @java.lang.Override
    public boolean hasReadWrite() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * default = 0 = read_write, 1 = read_only, 2 = write_only
     * </pre>
     *
     * <code>optional uint32 read_write = 1;</code>
     *
     * @return The readWrite.
     */
    @java.lang.Override
    public int getReadWrite() {
      return readWrite_;
    }

    /**
     * <pre>
     * default = 0 = read_write, 1 = read_only, 2 = write_only
     * </pre>
     *
     * <code>optional uint32 read_write = 1;</code>
     *
     * @param value The readWrite to set.
     * @return This builder for chaining.
     */
    public Builder setReadWrite(int value) {
      bitField0_ |= 0x00000001;
      readWrite_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * default = 0 = read_write, 1 = read_only, 2 = write_only
     * </pre>
     *
     * <code>optional uint32 read_write = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearReadWrite() {
      bitField0_ = (bitField0_ & ~0x00000001);
      readWrite_ = 0;
      onChanged();
      return this;
    }

    private int redBlue_;

    /**
     * <pre>
     * default = 0 = blue, 1 = red
     * </pre>
     *
     * <code>optional uint32 red_blue = 2;</code>
     *
     * @return Whether the redBlue field is set.
     */
    @java.lang.Override
    public boolean hasRedBlue() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <pre>
     * default = 0 = blue, 1 = red
     * </pre>
     *
     * <code>optional uint32 red_blue = 2;</code>
     *
     * @return The redBlue.
     */
    @java.lang.Override
    public int getRedBlue() {
      return redBlue_;
    }

    /**
     * <pre>
     * default = 0 = blue, 1 = red
     * </pre>
     *
     * <code>optional uint32 red_blue = 2;</code>
     *
     * @param value The redBlue to set.
     * @return This builder for chaining.
     */
    public Builder setRedBlue(int value) {
      bitField0_ |= 0x00000002;
      redBlue_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * default = 0 = blue, 1 = red
     * </pre>
     *
     * <code>optional uint32 red_blue = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRedBlue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      redBlue_ = 0;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ApbTxnProperties)
  }

  // @@protoc_insertion_point(class_scope:ApbTxnProperties)
  private static final com.arijo.protobuf.ApbTxnProperties DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.arijo.protobuf.ApbTxnProperties();
  }

  public static com.arijo.protobuf.ApbTxnProperties getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated
  public static final com.google.protobuf.Parser<ApbTxnProperties>
      PARSER = new com.google.protobuf.AbstractParser<ApbTxnProperties>() {
    @java.lang.Override
    public ApbTxnProperties parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApbTxnProperties(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApbTxnProperties> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApbTxnProperties> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arijo.protobuf.ApbTxnProperties getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

