// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbUpdateObjectsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbUpdateObjects)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ApbUpdateOp updates = 1;</code>
   */
  java.util.List<com.arijo.protobuf.ApbUpdateOp>
  getUpdatesList();

  /**
   * <code>repeated .ApbUpdateOp updates = 1;</code>
   */
  com.arijo.protobuf.ApbUpdateOp getUpdates(int index);

  /**
   * <code>repeated .ApbUpdateOp updates = 1;</code>
   */
  int getUpdatesCount();

  /**
   * <code>repeated .ApbUpdateOp updates = 1;</code>
   */
  java.util.List<? extends com.arijo.protobuf.ApbUpdateOpOrBuilder>
  getUpdatesOrBuilderList();

  /**
   * <code>repeated .ApbUpdateOp updates = 1;</code>
   */
  com.arijo.protobuf.ApbUpdateOpOrBuilder getUpdatesOrBuilder(
      int index);

  /**
   * <code>required bytes transaction_descriptor = 2;</code>
   *
   * @return Whether the transactionDescriptor field is set.
   */
  boolean hasTransactionDescriptor();

  /**
   * <code>required bytes transaction_descriptor = 2;</code>
   *
   * @return The transactionDescriptor.
   */
  com.google.protobuf.ByteString getTransactionDescriptor();
}
