// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

public interface ApbUpdateOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApbUpdateOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ApbCounterUpdate counterop = 1;</code>
   *
   * @return Whether the counterop field is set.
   */
  boolean hasCounterop();

  /**
   * <code>optional .ApbCounterUpdate counterop = 1;</code>
   *
   * @return The counterop.
   */
  com.arijo.protobuf.ApbCounterUpdate getCounterop();

  /**
   * <code>optional .ApbCounterUpdate counterop = 1;</code>
   */
  com.arijo.protobuf.ApbCounterUpdateOrBuilder getCounteropOrBuilder();

  /**
   * <code>optional .ApbSetUpdate setop = 2;</code>
   *
   * @return Whether the setop field is set.
   */
  boolean hasSetop();

  /**
   * <code>optional .ApbSetUpdate setop = 2;</code>
   *
   * @return The setop.
   */
  com.arijo.protobuf.ApbSetUpdate getSetop();

  /**
   * <code>optional .ApbSetUpdate setop = 2;</code>
   */
  com.arijo.protobuf.ApbSetUpdateOrBuilder getSetopOrBuilder();

  /**
   * <code>optional .ApbRegUpdate regop = 3;</code>
   *
   * @return Whether the regop field is set.
   */
  boolean hasRegop();

  /**
   * <code>optional .ApbRegUpdate regop = 3;</code>
   *
   * @return The regop.
   */
  com.arijo.protobuf.ApbRegUpdate getRegop();

  /**
   * <code>optional .ApbRegUpdate regop = 3;</code>
   */
  com.arijo.protobuf.ApbRegUpdateOrBuilder getRegopOrBuilder();

  /**
   * <code>optional .ApbMapUpdate mapop = 5;</code>
   *
   * @return Whether the mapop field is set.
   */
  boolean hasMapop();

  /**
   * <code>optional .ApbMapUpdate mapop = 5;</code>
   *
   * @return The mapop.
   */
  com.arijo.protobuf.ApbMapUpdate getMapop();

  /**
   * <code>optional .ApbMapUpdate mapop = 5;</code>
   */
  com.arijo.protobuf.ApbMapUpdateOrBuilder getMapopOrBuilder();

  /**
   * <code>optional .ApbCrdtReset resetop = 6;</code>
   *
   * @return Whether the resetop field is set.
   */
  boolean hasResetop();

  /**
   * <code>optional .ApbCrdtReset resetop = 6;</code>
   *
   * @return The resetop.
   */
  com.arijo.protobuf.ApbCrdtReset getResetop();

  /**
   * <code>optional .ApbCrdtReset resetop = 6;</code>
   */
  com.arijo.protobuf.ApbCrdtResetOrBuilder getResetopOrBuilder();

  /**
   * <code>optional .ApbFlagUpdate flagop = 7;</code>
   *
   * @return Whether the flagop field is set.
   */
  boolean hasFlagop();

  /**
   * <code>optional .ApbFlagUpdate flagop = 7;</code>
   *
   * @return The flagop.
   */
  com.arijo.protobuf.ApbFlagUpdate getFlagop();

  /**
   * <code>optional .ApbFlagUpdate flagop = 7;</code>
   */
  com.arijo.protobuf.ApbFlagUpdateOrBuilder getFlagopOrBuilder();

  /**
   * <code>optional .ApbMaxMinUpdate maxminop = 11;</code>
   *
   * @return Whether the maxminop field is set.
   */
  boolean hasMaxminop();

  /**
   * <code>optional .ApbMaxMinUpdate maxminop = 11;</code>
   *
   * @return The maxminop.
   */
  com.arijo.protobuf.ApbMaxMinUpdate getMaxminop();

  /**
   * <code>optional .ApbMaxMinUpdate maxminop = 11;</code>
   */
  com.arijo.protobuf.ApbMaxMinUpdateOrBuilder getMaxminopOrBuilder();

  /**
   * <code>optional .ApbTopkRmvUpdate topkrmvop = 12;</code>
   *
   * @return Whether the topkrmvop field is set.
   */
  boolean hasTopkrmvop();

  /**
   * <code>optional .ApbTopkRmvUpdate topkrmvop = 12;</code>
   *
   * @return The topkrmvop.
   */
  com.arijo.protobuf.ApbTopkRmvUpdate getTopkrmvop();

  /**
   * <code>optional .ApbTopkRmvUpdate topkrmvop = 12;</code>
   */
  com.arijo.protobuf.ApbTopkRmvUpdateOrBuilder getTopkrmvopOrBuilder();

  /**
   * <code>optional .ApbTopkUpdate topkop = 13;</code>
   *
   * @return Whether the topkop field is set.
   */
  boolean hasTopkop();

  /**
   * <code>optional .ApbTopkUpdate topkop = 13;</code>
   *
   * @return The topkop.
   */
  com.arijo.protobuf.ApbTopkUpdate getTopkop();

  /**
   * <code>optional .ApbTopkUpdate topkop = 13;</code>
   */
  com.arijo.protobuf.ApbTopkUpdateOrBuilder getTopkopOrBuilder();

  /**
   * <code>optional .ApbLeaderboardUpdate leaderboardop = 14;</code>
   *
   * @return Whether the leaderboardop field is set.
   */
  boolean hasLeaderboardop();

  /**
   * <code>optional .ApbLeaderboardUpdate leaderboardop = 14;</code>
   *
   * @return The leaderboardop.
   */
  com.arijo.protobuf.ApbLeaderboardUpdate getLeaderboardop();

  /**
   * <code>optional .ApbLeaderboardUpdate leaderboardop = 14;</code>
   */
  com.arijo.protobuf.ApbLeaderboardUpdateOrBuilder getLeaderboardopOrBuilder();

  /**
   * <code>optional .ApbAverageUpdate avgop = 15;</code>
   *
   * @return Whether the avgop field is set.
   */
  boolean hasAvgop();

  /**
   * <code>optional .ApbAverageUpdate avgop = 15;</code>
   *
   * @return The avgop.
   */
  com.arijo.protobuf.ApbAverageUpdate getAvgop();

  /**
   * <code>optional .ApbAverageUpdate avgop = 15;</code>
   */
  com.arijo.protobuf.ApbAverageUpdateOrBuilder getAvgopOrBuilder();
}
