// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: antidote.proto

package com.arijo.protobuf;

/**
 * Protobuf enum {@code CRDT_type}
 */
public enum CRDT_type
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COUNTER = 3;</code>
   */
  COUNTER(3),
  /**
   * <code>ORSET = 4;</code>
   */
  ORSET(4),
  /**
   * <code>LWWREG = 5;</code>
   */
  LWWREG(5),
  /**
   * <code>MVREG = 6;</code>
   */
  MVREG(6),
  /**
   * <code>GMAP = 8;</code>
   */
  GMAP(8),
  /**
   * <code>RWSET = 10;</code>
   */
  RWSET(10),
  /**
   * <code>RRMAP = 11;</code>
   */
  RRMAP(11),
  /**
   * <code>FATCOUNTER = 12;</code>
   */
  FATCOUNTER(12),
  /**
   * <code>FLAG_EW = 13;</code>
   */
  FLAG_EW(13),
  /**
   * <pre>
   * FLAG_DW = 14;
   * </pre>
   *
   * <code>TOPK = 1;</code>
   */
  TOPK(1),
  /**
   * <code>TOPK_RMV = 2;</code>
   */
  TOPK_RMV(2),
  /**
   * <code>AVG = 7;</code>
   */
  AVG(7),
  /**
   * <code>LEADERBOARD = 9;</code>
   */
  LEADERBOARD(9),
  /**
   * <code>MAXMIN = 0;</code>
   */
  MAXMIN(0),
  /**
   * <code>ORMAP = 15;</code>
   */
  ORMAP(15),
  /**
   * <code>TOPSUM = 14;</code>
   */
  TOPSUM(14),
  ;

  /**
   * <code>COUNTER = 3;</code>
   */
  public static final int COUNTER_VALUE = 3;
  /**
   * <code>ORSET = 4;</code>
   */
  public static final int ORSET_VALUE = 4;
  /**
   * <code>LWWREG = 5;</code>
   */
  public static final int LWWREG_VALUE = 5;
  /**
   * <code>MVREG = 6;</code>
   */
  public static final int MVREG_VALUE = 6;
  /**
   * <code>GMAP = 8;</code>
   */
  public static final int GMAP_VALUE = 8;
  /**
   * <code>RWSET = 10;</code>
   */
  public static final int RWSET_VALUE = 10;
  /**
   * <code>RRMAP = 11;</code>
   */
  public static final int RRMAP_VALUE = 11;
  /**
   * <code>FATCOUNTER = 12;</code>
   */
  public static final int FATCOUNTER_VALUE = 12;
  /**
   * <code>FLAG_EW = 13;</code>
   */
  public static final int FLAG_EW_VALUE = 13;
  /**
   * <pre>
   * FLAG_DW = 14;
   * </pre>
   *
   * <code>TOPK = 1;</code>
   */
  public static final int TOPK_VALUE = 1;
  /**
   * <code>TOPK_RMV = 2;</code>
   */
  public static final int TOPK_RMV_VALUE = 2;
  /**
   * <code>AVG = 7;</code>
   */
  public static final int AVG_VALUE = 7;
  /**
   * <code>LEADERBOARD = 9;</code>
   */
  public static final int LEADERBOARD_VALUE = 9;
  /**
   * <code>MAXMIN = 0;</code>
   */
  public static final int MAXMIN_VALUE = 0;
  /**
   * <code>ORMAP = 15;</code>
   */
  public static final int ORMAP_VALUE = 15;
  /**
   * <code>TOPSUM = 14;</code>
   */
  public static final int TOPSUM_VALUE = 14;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CRDT_type valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CRDT_type forNumber(int value) {
    switch (value) {
      case 3:
        return COUNTER;
      case 4:
        return ORSET;
      case 5:
        return LWWREG;
      case 6:
        return MVREG;
      case 8:
        return GMAP;
      case 10:
        return RWSET;
      case 11:
        return RRMAP;
      case 12:
        return FATCOUNTER;
      case 13:
        return FLAG_EW;
      case 1:
        return TOPK;
      case 2:
        return TOPK_RMV;
      case 7:
        return AVG;
      case 9:
        return LEADERBOARD;
      case 0:
        return MAXMIN;
      case 15:
        return ORMAP;
      case 14:
        return TOPSUM;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CRDT_type>
  internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<
      CRDT_type> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<CRDT_type>() {
        public CRDT_type findValueByNumber(int number) {
          return CRDT_type.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
  getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor
  getDescriptorForType() {
    return getDescriptor();
  }

  public static final com.google.protobuf.Descriptors.EnumDescriptor
  getDescriptor() {
    return com.arijo.protobuf.AntidotePB.getDescriptor().getEnumTypes().get(0);
  }

  private static final CRDT_type[] VALUES = values();

  public static CRDT_type valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CRDT_type(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:CRDT_type)
}

